Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,18 @@ jobs:
           branch: "master"
       - uses: reviewdog/action-setup@v1
 
-      - run: alr build --validation | ${{ env.REVIEWDOG_CMD }}
+      - run: |
+         alr build --validation > output.txt 2>&1 || status=$?
+         cat output.txt
+         cat output.txt | reviewdog -efm="%f:%l:%c: %m" -diff="git diff master" --reporter=github-pr-review
+         # Check for errors
+         if [ $status -ne 0 ]; then
+            echo "ERROR: gprbuild returned $status"
+            # This will cause the workflow to exit with $status
+            bash -c "exit $status"
+         fi
+        
+        # alr build --validation | ${{ env.REVIEWDOG_CMD }}
 
       - run: alr gnatprove -j0 --level=4 | ${{ env.REVIEWDOG_CMD }}
 
